# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d23d72656cfdf6e0f96a10f459e407ad0bf5c6a2b543b07a57c583cd1f455416f7cfcb96acc49fd185493bb0bae835911d26c2382f50f80ae7e2730da4d2a29

test:
  secret_key_base: c12b0b2fe520af399b6270b0ea1ee09512ef7077e7dd159c95bc5fa8c35dfd80b57938571eba0528889d310db9f8484aa8af8e7bcdb100bc628bad92d9531fdf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
